# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_shoppinglist_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
