# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_shoppinglistitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
