# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shoppinglistitem_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='warning_price',
            field=models.IntegerField(default=0),
        ),
    ]
