# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_shoppinglist_warning_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
